# Travis CI Configuration
sudo: required
services:
  - docker

before_install:
  - docker build -t czachman/react-test -f ./client/Dockerfile.dev ./client
  # build other projects here

# Test Running Section - any exit codes other than 0 --> test failed
script:
  - docker run czachman/react-test npm run test -- --coverage
  # -- --coverage ensures jest testing suite does not hang in watch mode
  # Add additional tests here

# Build Production Images and push to Docker Hub
after_success:
  - docker build -t czachman/multi-client ./client
  - docker build -t czachman/multi-server ./server
  - docker build -t czachman/multi-nginx ./nginx
  - docker build -t czachman/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # grabs environment variable and sends it in stdin to the next command
  # --password-stdin tells docker to look for password in stdin

  # Push Images to Docker Hub
  - docker push czachman/multi-client
  - docker push czachman/multi-server
  - docker push czachman/multi-nginx
  - docker push czachman/multi-worker
# Deploy to AWS Elastic Beanstalk
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "multi-docker"
#   env: MultiDocker-env
#   bucket_name: "elasticbeanstalk-us-east-2-279274087707"
#   bucket_path: "multi-docker"
#   on:
#     branch: master
#   access_key_id: "$AWS_ACCESS_KEY"
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
